version: '3.7'
services:
  cassandra_db:
    image: "cassandra:4.0"
    hostname: "cassandra_db"
    ports:
      - "9042:9042"
    networks:
      - "cassandra_data_modeling_network"
  development_environment:
    container_name: "development_environment_container"
    hostname: "development_environment"
    build:
      context: "."
      dockerfile: "./development_environment/Dockerfile"
    ports:
      - "8888:8888"
    networks:
      - "cassandra_data_modeling_network"
    volumes:
      - ".:/usr/src/app"
    depends_on:
      - "cassandra_db"
    command: sh -c "/wait && jupyter notebook --port=8888 --no-browser --ip=0.0.0.0 --allow-root"
    environment:
      WAIT_HOSTS: "cassandra_db:9042"
      WAIT_TIMEOUT: 120
      WAIT_SLEEP_INTERVAL: 5
      WAIT_HOST_CONNECT_TIMEOUT: 60
networks:
  cassandra_data_modeling_network:
